http.host: "0.0.0.0"
log.level: info

# Paths for the Logstash pipeline configuration
path.config: "/usr/share/logstash/pipeline/logstash.conf"

# Settings for log retention and monitoring
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# X-Pack Monitoring 설정
xpack.monitoring.enabled: true
xpack.monitoring.elasticsearch.hosts: ["https://elasticsearch.www.projectkkk.com:9200"]
xpack.monitoring.elasticsearch.username: "elastic"
xpack.monitoring.elasticsearch.password: "elastic"

# HTTP SSL 설정
http.ssl.keystore.path: "/usr/share/logstash/config/logstash.p12"
http.ssl.keystore.password: "Ccenter123456!"

# Elasticsearch output을 위한 SSL 설정
xpack.monitoring.elasticsearch.ssl.certificate_authority: ["/usr/share/logstash/config/logstash.p12"]
xpack.monitoring.elasticsearch.ssl.verification_mode: certificate
