cluster.name: es-cluster-prod
node.name: es-prod-1  # 노드 이름 명확화

# Network and Security Settings
network.host: 0.0.0.0
http.port: 9200

# Security Settings
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.http.ssl.enabled: true  # HTTP SSL 활성화 추가

# SSL Configuration
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elasticsearch.p12
xpack.security.transport.ssl.truststore.path: /usr/share/elasticsearch/config/certs/elasticsearch.p12
xpack.security.http.ssl.keystore.path: /usr/share/elasticsearch/config/certs/elasticsearch.p12
xpack.security.transport.ssl.keystore.secure_password: Ccenter123456!
xpack.security.transport.ssl.truststore.secure_password: Ccenter123456!
xpack.security.http.ssl.keystore.secure_password: Ccenter123456!
xpack.security.http.ssl.truststore.secure_password: Ccenter123456!

# Node Configuration
node.master: true
node.data: true
discovery.type: single-node  # 클러스터 구성 시 제거 필요

# Memory Settings
bootstrap.memory_lock: true