spring:
  datasource:
    url: jdbc:mysql://zigzag-database.cnkq8ww86ffm.ap-northeast-2.rds.amazonaws.com:3306/zigzagDB
    username: Kang
    password: alstj121!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl.auto: update
        use_sql_comments: true
        format_sql: true
        highlight_sql: true
        generate_statistics: true
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true

  elasticsearch:
    uris: https://elasticsearch.projectkkk.com:9200
    username: elastic
    password: elastic
    connection-timeout: 10000
    read-timeout: 60000
    ssl:
      keystore-path: /app/springboot.p12
      keystore-password: Ccenter123456!
      keystore-type: PKCS12
      key-password: Ccenter123456!
      verification-mode: full
      trust-store: /app/elasticsearch.p12
      trust-store-password: Ccenter123456!
      trust-store-type: PKCS12
    index-settings:
      index:
        analysis:
          analyzer:
            korean:
              type: nori
              tokenizer: nori_tokenizer
    index:
      auto-create: true
  data:
    elasticsearch:
      repositories:
        enabled: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: logs-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topics:
      kafka-logs: kafka-logs
      error-logs: error-logs


  logging:
    level:
      root: INFO
      com.project: INFO
      org.springframework.web: INFO
      org.hibernate.SQL: WARN
      org.hibernate.orm.jdbc.bind: WARN
      org.hibernate.type.descriptor.sql: INFO
      org.hibernate.stat: WARN
      org.hibernate.SQL_SLOW: WARN
      org.hibernate.cache: WARN
      org.springframework.batch: DEBUG

  server:
    port: 443
    ssl:
      key-store: /app/springboot.p12
      key-store-password: Ccenter123456!
      key-store-type: PKCS12
    hsts:
      enabled: true
      include-sub-domains: true
      max-age: 31536000

  mail:
    host: smtp.gmail.com
    port: 587
    username: sksdmltkek14@gmail.com
    password: ixcv bizi nhbl zzcc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
