spring:
  profiles:
    active: local # 기본 활성화 프로파일 설정 (local)

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://zigzag-database.cnkq8ww86ffm.ap-northeast-2.rds.amazonaws.com:3306/zigzagDB
    username: Kang
    password: ${DB_PASSWORD} # 데이터베이스 비밀번호 환경 변수
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 로컬에서만 사용하는 옵션
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true # 개발 중 SQL 쿼리 로그 활성화
        format_sql: true # 포맷팅된 SQL 출력
  elasticsearch:
    rest:
      uris: https://elasticsearch.projectkkk.com:9200
      username: elastic
      password: ${ELASTIC_PASSWORD} # Elasticsearch 비밀번호 환경 변수
      connection-timeout: 60s
      socket-timeout: 30s
      ssl:
        enabled: true
        trust-store-type: PKCS12
        trust-store: /app/elastic-stack-ca.p12
        trust-store-password: ${TRUSTSTORE_PASSWORD} # Truststore 비밀번호 환경 변수
        key-store: /app/springboot.p12
        key-store-password: ${KEYSTORE_PASSWORD} # Keystore 비밀번호 환경 변수
        key-store-type: PKCS12
  kafka:
    bootstrap-servers: kafka:9092
  server:
    port: 8080 # 로컬에서는 8080 포트 사용
    ssl:
      enabled: false # 로컬 개발 시 SSL 비활성화
  logging:
    level:
      root: DEBUG # 로컬 개발 로그 디버그 수준

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://dev-database:3306/zigzagDB
    username: devuser
    password: devpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: true
  elasticsearch:
    rest:
      uris: https://elasticsearch.dev:9200
      username: elastic
      password: devpassword
      connection-timeout: 60s
      socket-timeout: 30s
      ssl:
        enabled: true
        trust-store-type: PKCS12
        trust-store: /app/elastic-stack-ca.p12
        trust-store-password: devpassword
        key-store: /app/springboot.p12
        key-store-password: devpassword
        key-store-type: PKCS12
  kafka:
    bootstrap-servers: kafka:9092
  server:
    port: 443
    ssl:
      enabled: true
      key-store: /app/springboot.p12
      key-store-password: devpassword
      key-store-type: PKCS12
  logging:
    level:
      root: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://zigzag-database.cnkq8ww86ffm.ap-northeast-2.rds.amazonaws.com:3306/zigzagDB
    username: Kang
    password: alstj121!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: false
  elasticsearch:
    rest:
      uris: https://elasticsearch.projectkkk.com:9200
      username: elastic
      password: ${ELASTIC_PASSWORD}
      connection-timeout: 60s
      socket-timeout: 30s
      ssl:
        enabled: true
        trust-store-type: PKCS12
        trust-store: /app/elastic-stack-ca.p12
        trust-store-password: ${CA_PASSWORD}
        key-store: /app/springboot.p12
        key-store-password: ${KEYSTORE_PASSWORD}
        key-store-type: PKCS12
  kafka:
    bootstrap-servers: kafka:9092
  server:
    port: 443
    ssl:
      enabled: true
      key-store: /app/springboot.p12
      key-store-password: ${KEYSTORE_PASSWORD}
      key-store-type: PKCS12

    hsts:
      enabled: true
      include-sub-domains: true
      max-age: 31536000
  logging:
    level:
      root: INFO
