server.name: kibana-prod
server.host: "0.0.0.0"
server.port: 5601

elasticsearch.hosts: ["https://elasticsearch.www.projectkkk.com:9200"]
elasticsearch.username: "elastic"
elasticsearch.password: "elastic"

server.ssl.enabled: true
server.ssl.certificate: "/usr/share/kibana/config/kibana.pem"
server.ssl.key: "/usr/share/kibana/config/kibana.pem"

elasticsearch.ssl.certificateAuthorities: ["/usr/share/kibana/config/kibana.pem"]
elasticsearch.ssl.verificationMode: "certificate"

xpack.security.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "z3j42kT0Vw48Fj7ZGNdYZmAxfjR8iAn2P1cH3N0LVJU="

i18n.locale: "ko"
